Deploy to dev using pipeline task (#105)
* add pipeline deploy step

* Remove code deployment with terraform

Terraform deployment should not deploy to auth server and stage slot
directly. This is noted to be unreliable way of deploying. This commit
removes application_stack argument to terraform resource deployment to
deploy docker image through pipeline. Addional variables are added to
output the terraform values to be used in pipeline.

* Update workflow

Actions workflow is included to have url test after code deployment and
dynamics setting of environment variables for terraform and code deploym
ent.

diff --git a/.github/workflows/actions/deploy-environment/action.yml b/.github/workflows/actions/deploy-environment/action.yml
--- a/.github/workflows/actions/deploy-environment/action.yml
+++ b/.github/workflows/actions/deploy-environment/action.yml
@@ -35,6 +35,7 @@ runs:
       run: |
         KEY_VAULT_NAME=$(jq -r '.key_vault_name' $TFVARS)
         RESOURCE_GROUP_NAME=$(jq -r '.resource_group_name' $TFVARS)
+        RESOURCE_PREFIX=$(jq -r '.resource_prefix' $TFVARS)
 
         if [ -z "$KEY_VAULT_NAME" ]; then
           echo "::error ::Failed to extract key_vault_name from $TFVARS"
@@ -46,8 +47,14 @@ runs:
           exit 1
         fi
 
+        if [ -z "$RESOURCE_PREFIX" ]; then
+          echo "::error ::Failed to extract resource_prefix from $TFVARS"
+          exit 1
+        fi
+
         echo ::set-output name=resource_group_name::$RESOURCE_GROUP_NAME
         echo ::set-output name=key_vault_name::$KEY_VAULT_NAME
+        echo ::set-output name=resource_prefix::$RESOURCE_PREFIX
 
       shell: bash
       env:
@@ -75,8 +82,47 @@ runs:
         make ci ${{ inputs.environment_name }} terraform-apply
         cd terraform && echo ::set-output name=url::https://$(terraform output -raw auth_server_fqdn)/
         echo ::set-output name=postgres_server_name::$(terraform output -raw postgres_server_name)
+        echo ::set-output name=blue_green::$(terraform output -raw blue_green)
+
+        if [ "$blue_green" = "true" ]; then
+          echo ::set-output name=slot_name::$(terraform output -raw web_app_slot_name)
+        else
+          echo ::set-output name=slot_name::production
+        fi
       env:
         ARM_ACCESS_KEY: ${{ steps.get_secrets.outputs.TFSTATE-CONTAINER-ACCESS-KEY }}
         TF_VAR_azure_sp_credentials_json: ${{ inputs.azure_credentials }}
         IMAGE_TAG: ${{ inputs.image_tag }}
       shell: bash
+
+    - uses: azure/webapps-deploy@v2
+      with:
+        app-name: ${{ steps.config.outputs.resource_prefix }}getanid-${{ inputs.environment_name}}-auths-app
+        images: ghcr.io/dfe-digital/get-an-identity:authserver-${{ github.sha }}
+        slot-name: ${{ steps.terraform.outputs.slot_name }}
+
+    - uses: azure/CLI@v1
+      if: ${{ steps.terraform.outputs.blue_green == 'true' }}
+      with:
+        inlineScript: |
+          az webapp deployment slot swap  -g ${{ steps.config.outputs.resource_group_name }} -n ${{ steps.config.outputs.resource_prefix }}getanid-${{ inputs.environment_name}}-auths-app --slot ${{ steps.terraform.outputs.slot_name}} --target-slot production
+
+    - name: Check new site is up
+      run: |
+        attempt_counter=0
+        max_attempts=60
+        SHA_URL=https://${{ steps.config.outputs.resource_prefix }}getanid-${{ inputs.environment_name }}-auths-app.azurewebsites.net/_sha
+        APP_SHA=$(curl $SHA_URL)
+        until [[ "$EXPECTED_SHA" == "$APP_SHA" ]]; do
+            if [ ${attempt_counter} -eq ${max_attempts} ];then
+              echo "Max attempts reached"
+              exit 1
+            fi
+            APP_SHA=$(curl $SHA_URL)
+            printf '.'
+            attempt_counter=$(($attempt_counter+1))
+            sleep 5
+        done
+      shell: bash
+      env:
+        EXPECTED_SHA: ${{ inputs.image_tag }}
