Add blue/green deployment (#59)
* Add swap slot for apps

Get an Identity app deployments in preprod and production should use
app service swap deployment capability. This ensures that apps are
deployed and smoke tested before swapping to production slot. This
commit adds terraform confiuration to deploy staging slot along with the
apps in preprod and production.

* Add environment deployment jobs

Deployment to Azure app service for all environments of Get an Identity
is configured through Terraform deployment files. Preprod and production
jobs have a staging slot that is used for blue/green deployments.

* Modify Makefile

PaaS authentication code is no longer needed for terraform steps as the
deployment is on Azure. Additional IMAGE_TAG is required to pass Github
SHA which is required in Terraform to deploy the correct docker image on
deployments.

diff --git a/.github/workflows/actions/deploy-environment/action.yml b/.github/workflows/actions/deploy-environment/action.yml
--- a/.github/workflows/actions/deploy-environment/action.yml
+++ b/.github/workflows/actions/deploy-environment/action.yml
@@ -4,14 +4,8 @@ inputs:
   environment_name:
     description: 'The name of the environment'
     required: true
-  docker_image:
-    description: 'Auth server Docker image to deploy to the app service'
-    required: true
-  authserver_tag:
-    description: 'Test client Docker image to deploy to the app service'
-    required: true
-  testclient_tag:
-    description: 'Test client Docker image to deploy to the app service'
+  image_tag:
+    description: 'github SHA of the image'
     required: true
   azure_credentials:
     description: 'JSON object containing a service principal that can read from Azure Key Vault'
@@ -27,6 +21,9 @@ outputs:
   environment_url:
     description: 'The base URL for the deployed environment'
     value: ${{ steps.terraform.outputs.url }}
+  postgres_server_name:
+    description: The name of the postgres server deployed
+    value: ${{ steps.terraform.outputs.postgres_server_name }}
 
 
 runs:
@@ -37,12 +34,21 @@ runs:
       id: config
       run: |
         KEY_VAULT_NAME=$(jq -r '.key_vault_name' $TFVARS)
-        PAAS_SPACE=$(jq -r '.paas_space' $TFVARS)
+        RESOURCE_GROUP_NAME=$(jq -r '.resource_group_name' $TFVARS)
+
         if [ -z "$KEY_VAULT_NAME" ]; then
           echo "::error ::Failed to extract key_vault_name from $TFVARS"
           exit 1
         fi
+
+        if [ -z "$RESOURCE_GROUP_NAME" ]; then
+          echo "::error ::Failed to extract resource_group_name from $TFVARS"
+          exit 1
+        fi
+
+        echo ::set-output name=resource_group_name::$RESOURCE_GROUP_NAME
         echo ::set-output name=key_vault_name::$KEY_VAULT_NAME
+
       shell: bash
       env:
         TFVARS: ${{ inputs.terraform_vars }}
@@ -67,11 +73,21 @@ runs:
       id: terraform
       run: |
         make ci ${{ inputs.environment_name }} terraform-apply
-        cd terraform && echo ::set-output name=url::https://$(terraform output -raw auth_server_fqdn)/
+        cd terraform && echo ::set-output name=url::$(terraform output -raw auth_server_fqdn)/
+        echo ::set-output name=postgres_server_name::$(terraform output -raw postgres_server_name)
       env:
         ARM_ACCESS_KEY: ${{ steps.get_secrets.outputs.TFSTATE-CONTAINER-ACCESS-KEY }}
         TF_VAR_azure_sp_credentials_json: ${{ inputs.azure_credentials }}
-        TF_VAR_docker_image: ${{ inputs.docker_image }}
-        TF_VAR_authserver_tag: ${{ inputs.authserver_tag }}
-        TF_VAR_testclient_tag: ${{ inputs.testclient_tag }}
+        IMAGE_TAG: ${{ inputs.image_tag }}
       shell: bash
+
+    - name: Public IP
+      id: ip
+      uses: haythem/public-ip@v1.2
+
+    # - name: Azure CLI script
+    #   uses: azure/CLI@v1
+    #   with:
+    #     azcliversion: 2.30.0
+    #     inlineScript: |
+    #       az postgres flexible-server firewall-rule create --name ${{ steps.terraform.outputs.postgres_server_name }} --resource-group ${{ steps.config.outputs.resource_group_name }} --rule-name Allow-GithubRunner --start-ip-address ${{ steps.ip.outputs.ipv4 }} --end-ip-address ${{ steps.ip.outputs.ipv4 }}
